name: "Set up and Archive"
description: "Set up and archive the project"
inputs:
  xcode-configuration:
    description: "Build configuration of Xcode, either Debug or Release"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/setup
      name: Setup
      with:
        xcode-configuration: ${{ inputs.xcode-configuration }}
    - uses: ./.github/workflows/archive
      name: Archive
      with:
        xcode-configuration: "${{ inputs.xcode-configuration }}"
    - name: Upload to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "RNPrebuilt-${{ inputs.xcode-configuration }}"
        path: "RNPrebuilt-${{ inputs.xcode-configuration }}.tar.gz"
