# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'ReactNative-Binary', configuration: 'Release'
  pod 'ReactNative-Binary-Debug', configuration: 'Debug' # loading debug support
end
