# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'RNPrebuilt', '0.69.1+hermesenabled', configuration: 'Release'
  pod 'RNPrebuilt-Debug', '0.69.1+hermesenabled', configuration: 'Debug' # loading debug support
end
